[tool.black]
line-length = 100
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["luxuryconnect", "accounts", "core", "catalog", "ai"]
multi_line_output = 3
include_trailing_comma = true

[tool.mypy]
python_version = 3.12
